### ISSUE TITLE
TypeError: done is not a function

### ISSUE THREAD

**Issue by chanakairugal** [haithembelhaj/compass-importer#12]
Hey, Why this error occur every time i try to compile. can u please help me out.
Im working with Angule-CLI
Node V4.4.5

G:\Workspaces\ng_testAppV2\node_modules\compass-importer\index.js:28
  return done({file: resolve(libPath,  path)})
         ^

TypeError: done is not a function
    at Object.importer (G:\Workspaces\ng_testAppV2\node_modules\compass-importer\index.js:28:10)
    at options.importer (G:\Workspaces\ng_testAppV2\node_modules\node-sass\lib\index.js:383:31)
    at Object.module.exports.renderSync (G:\Workspaces\ng_testAppV2\node_modules\node-sass\lib\index.js:406:23)
    at CompassPlugin.compile (G:\Workspaces\ng_testAppV2\node_modules\angular-cli\lib\broccoli\angular-broccoli-compass.js:43:23)
    at G:\Workspaces\ng_testAppV2\node_modules\angular-cli\lib\broccoli\angular-broccoli-compass.js:31:12
    at Array.forEach (native)
    at CompassPlugin.build (G:\Workspaces\ng_testAppV2\node_modules\angular-cli\lib\broccoli\angular-broccoli-compass.js:29:24)
    at G:\Workspaces\ng_testAppV2\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (G:\Workspaces\ng_testAppV2\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (G:\Workspaces\ng_testAppV2\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (G:\Workspaces\ng_testAppV2\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (G:\Workspaces\ng_testAppV2\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by haithembelhaj** [comment]
What's the node-sass version?

**Comment by chanakairugal** [comment]
^3.8.0

**Comment by haithembelhaj** [comment]
I wasn't aware of the fact that the `node-sass` `renderSync` function works differently as the async version.

I fixed the issue and published a new version. 
Thank you for reporting this :)

**Comment by chanakairugal** [comment]
No worries mate. waiting to hear from you about the update :100:  :)
